STARTUP = {
    "id": "demo-startup-1",
    "name": "AgriSense AI",
    "district": "Visakhapatnam",
    "sector": "AgriTech",
    "stage": "MVP",
    "dpiit": "DIPP123456",
    "team": 4,
    "description": "AI-powered crop disease detection and yield prediction for small farmers using computer vision and IoT.",
    "users": "Small and marginal farmers across Andhra Pradesh coastal districts",
    "pilot": "Actively seeking district-level pilots",
    "mentorshipNeed": "GTM strategy and government sales",
}

DEMO_STARTUPS = [
    STARTUP,
    {
        "id": "demo-startup-2",
        "name": "SkillBridge Rural",
        "district": "Vijayawada",
        "sector": "EdTech",
        "stage": "MVP",
        "dpiit": "DIPP789012",
        "team": 6,
        "description": "Vernacular skill training platform connecting rural youth with certified vocational courses via low-bandwidth mobile.",
        "users": "Rural youth (18-30) in Vijayawada, Guntur, and Kurnool districts",
        "pilot": "Yes, actively seeking",
        "mentorshipNeed": "Revenue model and district government partnerships",
    },
    {
        "id": "demo-startup-3",
        "name": "MedReach AP",
        "district": "Tirupati",
        "sector": "HealthTech",
        "stage": "Growth",
        "dpiit": "DIPP345678",
        "team": 9,
        "description": "Telemedicine and diagnostic AI connecting rural primary health centres with specialist doctors in AP hospitals.",
        "users": "PHC patients and ASHA workers in underserved AP mandals",
        "pilot": "Yes, pilot in progress",
        "mentorshipNeed": "Government health department integration and insurance empanelment",
    },
    {
        "id": "demo-startup-4",
        "name": "GovChain AP",
        "district": "Vijayawada",
        "sector": "GovTech",
        "stage": "Prototype",
        "dpiit": "",
        "team": 3,
        "description": "Blockchain-based land records and property tax management system for AP municipal corporations.",
        "users": "Municipal officials and property owners in AP tier-2 cities",
        "pilot": "Maybe, exploring",
        "mentorshipNeed": "Government sales and procurement process guidance",
    },
    {
        "id": "demo-startup-5",
        "name": "SolarVillage AP",
        "district": "Anantapur",
        "sector": "CleanTech",
        "stage": "Prototype",
        "dpiit": "",
        "team": 5,
        "description": "Community solar microgrids with IoT-based energy management for off-grid villages in Rayalaseema.",
        "users": "Rural villages without reliable grid electricity in Anantapur and Kurnool",
        "pilot": "Yes, actively seeking",
        "mentorshipNeed": "CleanTech funding and renewable energy policy navigation",
    },
]

READINESS = {
    "overall": 74,
    "band": "Near Ready",
    "mentorDomain": "AgriTech and government pilots",
    "scores": [
        {"label": "Innovation", "value": 82, "color": "#0f6e56"},
        {"label": "Market", "value": 68, "color": "#ba7517"},
        {"label": "Technology", "value": 79, "color": "#534ab7"},
        {"label": "Pilot", "value": 71, "color": "#0f6e56"},
        {"label": "Funding", "value": 64, "color": "#d85a30"},
    ],
    "strengths": ["Strong technical MVP", "Clear farmer user segment", "Relevant AP agriculture use case"],
    "gaps": ["Pilot validation evidence missing", "GTM strategy needs clarity", "Funding narrative needs refinement"],
    "nextSteps": ["Run district-level pilot", "Meet AgriTech mentor", "Complete GTM module"],
}

OPPORTUNITIES = [
    {
        "title": "AP Smart Agriculture Pilot 2026",
        "type": "Pilot",
        "sponsor": "RTIH + APIS",
        "match": 96,
        "deadline": "30 Jun 2026",
        "reasons": ["Sector fit", "Pilot interest aligned", "DPIIT-recognized startup"],
    },
    {
        "title": "AgriTech Expert Mentor - Dr. Venkat Rao",
        "type": "Mentor",
        "sponsor": "School of Design Thinking",
        "match": 91,
        "deadline": "Ongoing",
        "reasons": ["Mentor domain fit", "GTM need aligned", "Government sales expertise"],
    },
    {
        "title": "Startup India Seed Fund",
        "type": "Grant",
        "sponsor": "Startup India",
        "match": 82,
        "deadline": "15 Jul 2026",
        "reasons": ["Stage fit", "Funding readiness gap", "DPIIT eligibility"],
    },
    {
        "title": "NASSCOM DeepTech Cohort 2026",
        "type": "Program",
        "sponsor": "NASSCOM",
        "match": 76,
        "deadline": "20 Jun 2026",
        "reasons": ["AI/ML fit", "Technical MVP available", "Scale-up support"],
    },
]

MENTORS = [
    {
        "id": "mentor-1",
        "name": "Dr. Venkat Rao",
        "domain": "AgriTech & GTM",
        "title": "Former ICAR Director, AgriTech GTM Expert",
        "expertise": ["GTM strategy", "government sales", "crop technology"],
        "availability": "4 slots/week",
        "sectors": ["AgriTech", "CleanTech"],
        "stages": ["MVP", "Pilot", "Revenue"],
    },
    {
        "id": "mentor-2",
        "name": "Priya Nair",
        "domain": "EdTech & Digital Skills",
        "title": "Ex-NASSCOM, Digital Skills Architect",
        "expertise": ["EdTech product design", "rural digital access", "revenue models"],
        "availability": "3 slots/week",
        "sectors": ["EdTech", "GovTech"],
        "stages": ["Prototype", "MVP", "Pilot"],
    },
    {
        "id": "mentor-3",
        "name": "Dr. Ravi Chandra",
        "domain": "HealthTech & Public Health",
        "title": "Former NHM Director AP, Health Systems Expert",
        "expertise": ["government health integration", "insurance empanelment", "PHC workflows"],
        "availability": "2 slots/week",
        "sectors": ["HealthTech"],
        "stages": ["Pilot", "Revenue", "Growth"],
    },
    {
        "id": "mentor-4",
        "name": "Meera Krishnamurthy",
        "domain": "GovTech & e-Governance",
        "title": "AP e-Governance Society, Digital India Architect",
        "expertise": ["government procurement", "blockchain governance", "land records"],
        "availability": "5 slots/week",
        "sectors": ["GovTech", "DeepTech"],
        "stages": ["Prototype", "MVP"],
    },
    {
        "id": "mentor-5",
        "name": "Suresh Babu Reddy",
        "domain": "CleanTech & Energy Policy",
        "title": "Renewable Energy Policy Expert, MNRE",
        "expertise": ["CleanTech funding", "energy policy navigation", "community microgrids"],
        "availability": "3 slots/week",
        "sectors": ["CleanTech"],
        "stages": ["Prototype", "MVP", "Pilot"],
    },
    {
        "id": "mentor-6",
        "name": "Anita Desai",
        "domain": "Funding & Investor Relations",
        "title": "Angel Investor, 40+ startup investments",
        "expertise": ["seed funding", "DPIIT grants", "investor pitch coaching"],
        "availability": "2 slots/week",
        "sectors": ["All"],
        "stages": ["MVP", "Pilot", "Revenue"],
    },
]

COHORTS = [
    {
        "id": "cohort-2024",
        "name": "Cohort 2 — GovTech & CleanTech",
        "program": "RTIH Accelerator 2024",
        "status": "Completed",
        "start_date": "Feb 2024",
        "end_date": "Jun 2024",
        "startup_ids": ["demo-startup-4", "demo-startup-5"],
        "startup_names": ["GovChain AP", "SolarVillage AP"],
        "outcomes": {"pilots_launched": 1, "grants_won": 2, "mentor_hours": 48},
    },
    {
        "id": "cohort-2025",
        "name": "Cohort 3 — AgriTech & HealthTech",
        "program": "RTIH Accelerator 2025",
        "status": "Completed",
        "start_date": "Mar 2025",
        "end_date": "Jul 2025",
        "startup_ids": ["demo-startup-1", "demo-startup-3"],
        "startup_names": ["AgriSense AI", "MedReach AP"],
        "outcomes": {"pilots_launched": 2, "grants_won": 3, "mentor_hours": 72},
    },
    {
        "id": "cohort-2026",
        "name": "Cohort 4 — EdTech & AI Focus",
        "program": "RTIH Accelerator 2026",
        "status": "Active",
        "start_date": "Feb 2026",
        "end_date": "Jun 2026",
        "startup_ids": ["demo-startup-2", "demo-startup-1"],
        "startup_names": ["SkillBridge Rural", "AgriSense AI"],
        "outcomes": {"pilots_launched": 0, "grants_won": 1, "mentor_hours": 36},
    },
]

LIVE_FEED = [
    {"id": 1, "type": "match", "startup": "MedReach AP", "message": "matched with 3 new health pilot programs", "time": "2 min ago"},
    {"id": 2, "type": "score", "startup": "AgriSense AI", "message": "readiness score improved to 81 — now Ready", "time": "14 min ago"},
    {"id": 3, "type": "session", "startup": "SkillBridge Rural", "message": "mentor session with Priya Nair completed", "time": "1 hr ago"},
    {"id": 4, "type": "onboard", "startup": "GovChain AP", "message": "completed onboarding and profile setup", "time": "2 hr ago"},
    {"id": 5, "type": "grant", "startup": "SolarVillage AP", "message": "applied to Startup India Seed Fund", "time": "3 hr ago"},
    {"id": 6, "type": "pilot", "startup": "MedReach AP", "message": "pilot with Tirupati PHC network approved", "time": "4 hr ago"},
    {"id": 7, "type": "match", "startup": "AgriSense AI", "message": "matched with AP Smart Agriculture Pilot 2026", "time": "5 hr ago"},
    {"id": 8, "type": "score", "startup": "GovChain AP", "message": "completed DPIIT recognition module", "time": "6 hr ago"},
    {"id": 9, "type": "session", "startup": "AgriSense AI", "message": "1-on-1 with Dr. Venkat Rao — pilot planning", "time": "8 hr ago"},
    {"id": 10, "type": "onboard", "startup": "New Startup", "message": "joined from Kurnool — FinTech sector registered", "time": "10 hr ago"},
]

ADMIN_DASHBOARD = {
    "metrics": {
        "totalStartups": 132,
        "pilotReady": 24,
        "learningPaths": 89,
        "mentorSessions": 56,
    },
    "sectors": [
        {"name": "AgriTech", "value": 28, "color": "#0f6e56"},
        {"name": "EdTech", "value": 22, "color": "#534ab7"},
        {"name": "HealthTech", "value": 17, "color": "#d85a30"},
        {"name": "GovTech", "value": 15, "color": "#2673d9"},
        {"name": "DeepTech", "value": 18, "color": "#ba7517"},
    ],
    "stages": [
        {"stage": "Idea", "startups": 18},
        {"stage": "Prototype", "startups": 31},
        {"stage": "MVP", "startups": 46},
        {"stage": "Pilot", "startups": 24},
        {"stage": "Revenue", "startups": 13},
    ],
    "districts": [
        {"name": "Visakhapatnam", "count": 24, "growth": "+18%"},
        {"name": "Vijayawada", "count": 21, "growth": "+14%"},
        {"name": "Tirupati", "count": 17, "growth": "+11%"},
        {"name": "Guntur", "count": 15, "growth": "+9%"},
        {"name": "Kurnool", "count": 12, "growth": "+6%"},
        {"name": "Anantapur", "count": 10, "growth": "+4%"},
    ],
    "pilotQueue": [
        ["AgriSense AI", "AgriTech", "Visakhapatnam", "74", "Near Ready"],
        ["MedReach AP", "HealthTech", "Tirupati", "81", "Ready"],
        ["SkillBridge Rural", "EdTech", "Vijayawada", "78", "Near Ready"],
    ],
}
